export const dataOffline = [
    {
        '0': 0,
        convocatoriaId: 'LSnQkR8taTTxYTCkij8N',
        dataConvocatoriaId: '031kpWtcA1wFYLEHgDic',
        'REGIONAL ATLÁNTICO-3314059-15-09-2025.xls':
            'REGIONAL ATLÁNTICO-3315969-07-09-2025.xls',
        NIS: '36931893',
        TIPO_DOC: 'CC',
        DOCUMENTO: '1002160527',
        NOMBRES: 'ANGEL GABRIEL',
        APELLIDOS: 'PACHECO-ARIZA',
        CORREO_E: 'angelpacheco2002@hotmail.com',
        TEL_FIJO: '',
        TEL_MOVIL: '',
        TIPO_PRUEBA: 'Digital OnLine',
        RESULTADO_PRUEBA: '40,93',
        FECHA_CARGUE: '05/09/2025 15:44:52',
        ESTADO_PRUEBA: 'FINALIZADA POR USUARIO',
        MOTIVO_PRUEBA: 'Finalizacion de la prueba',
        FECHA_PRUEBA: '05/09/2025 03:21:43 PM',
        'ACCESO PREFERENTE': '',
        DIGITO: '7',
        DIA_PICO_PLACA: 'Dia   1-PROGRAMACION',
        'NOMBRE REPORTE': 'REPORTE DE CARGUE DE RESULTADOS',
        FECHA: '07/09/2025 18:46:11',
        FASE: '1',
        'CODIGO REGIONAL': '8',
        'NOMBRE REGIONAL': 'REGIONAL ATLÁNTICO',
        'CODIGO MUNICIPIO': '57008001',
        'NOMBRE MUNICIPIO': 'BARRANQUILLA',
        'CODIGO SEDE': '9302',
        'NOMBRE SEDE': 'CENTRO DE COMERCIO Y SERVICIOS',
        'CODIGO PROGRAMA': '123101',
        'DENOMINACION PROGRAMA': 'GESTION CONTABLE Y DE INFORMACION FINANCIERA',
        'CODIGO FICHA': '3315969',
        'ESTADO FICHA': 'En Inscripción',
        JORNADA: 'DIURNA',
        'NIVEL FORMACION': 'TECNÓLOGO',
        'CUPO FICHA': '30',
        'TOTAL INSCRITOS': '113',
        ESTADO: '',
        DESCRIPCION: '',
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiTEFSQVBFIiwib3duZXJJZCI6MSwicHJvZmlsZUlkIjoxLCJ0eXBlVXNlciI6InVzZXIiLCJpYXQiOjE3NDI1MDIxNDEsImV4cCI6MTc0MjUwNTc0MX0.X0ptAEuvE-z6TLCsPkoiSdW6LA77pF49QWmEkfcn0vY',
    },
];
